config/routes.rb
Rails.application.routes.draw do
  get 'friends/index'

  get 'friends/destroy'

  resources :friend_requests
  get 'friends/index'

  get 'friends/destroy'

  resources :friend_requests
  get "search_friends" => 'search_friends#index'

  get "profile/:id", to: "users#show", as: 'profile'

  resources :friendships
  devise_for :users, controllers: {registrations: "registrations", sessions: "sessions"}
  
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  put "/friend_requests/:id/create", to: "friend_requests#create"
  get "friend_requests/index"

  get 'home/index'
  root 'home#index'

end

app/models/friend_request.rb
class FriendRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def accept
    user.friends << friend
    destroy
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  private

  def create_inverse_relationship
    friend.friendships.create(friend: user)
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :rememberable

  belongs_to :user

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_attached_file :image,   
  :storage => :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  :dropbox_options => {       
    :path => proc { |style| "#{style}/#{id}_#{image.original_filename}"},      
    :unique_filename => true   
  }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_attached_file :portada,   
  :storage => :dropbox, :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
  :dropbox_options => {       
    :path => proc { |style| "#{style}/#{id}_#{portada.original_filename}"},      
    :unique_filename => true   
  }
  validates_attachment_content_type :portada, content_type: /\Aimage\/.*\Z/

  def update_with_password(params={}) 
    if params[:password].blank? 
      params.delete(:password) 
      params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    end 
    update_attributes(params) 
  end

  def email_required?
    false
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end
  
  validates :username, presence: true, uniqueness: true, length: {in: 5..20, too_short: "Minimo 5 caracteres", too_long: "Maximo 20 caracteres"},
  format: {with: /([A-Za-z0-9\-\_]+)/, message: "El nombre de usuario solo puede contener letras, numeros y guiones"}

   private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :user_id

  def user_id
     @user = User.find(current_user.id) if
          user_signed_in?
  end
 

  private 

  def set_last_request_at 
    current_user.update_attribute(:last_request_at, Time.now) if 
	user_signed_in? 
  end 
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
	before_action :set_friend_request, except: [:index, :create]
	before_action :set_friend, only: :destroy

	def index
	   @users = User.where("id NOT in (select friend_id from friend_requests where user_id=?) and id not in (?)",current_user,current_user).order("first_name ASC")
	end

	def create
		friend = User.find(params[:id])
		@friend_request = current_user.friend_requests.new(friend: friend)

		if @friend_request.save
		  redirect_to '/friend_requests'
		else
		  render json: @friend_request.errors, status: :unprocessable_entity
		end
	end

	def update
	  @friend_request.accept
	  head :no_content
	end

  private

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  end

  	def destroy
	  current_user.remove_friend(@friend)
	  head :no_content
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		super
	end
	def create
		super
	end
	def update
		super
	end

	private

	def sign_up_params
		allow = [:email, :password, :password_confirmation, :username, :first_name, :last_name, :image, :portada]
		params.require(resource_name).permit(allow)
	end

	def account_update_params
    	allow = [:email, :password, :password_confirmation, :username, :first_name, :last_name, :image, :portada]
		params.require(resource_name).permit(allow)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
before_filter :update_session_state, only: [:destroy]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
    super
       
   end

  # DELETE /resource/sign_out
   def destroy
     super    
   end

  protected

  def update_session_state
      
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
      @user = User.find(current_user.id)
      @users = User.where.not("id = ?",current_user.id).order("first_name ASC")       
  end
  def show
    @profiles = User.where("id in (select friend_id from friend_requests where user_id=?) and id not in (?)",current_user,current_user).order("first_name ASC")
  	@user_profile = User.find(params[:id])  
  	respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @user }
    end	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def self_or_other(message)
    message.user == current_user ? "self" : "other"
  end

  def message_interlocutor(message)
    message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
  end
end

app/helpers/search_friends_helper.rb
module SearchFriendsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def conversation_interlocutor(conversation)
    	conversation.recipient == current_user ? conversation.sender : conversation.recipient
  	end
  	
  	def resource_name
    :user
	end

	def resource
	@resource ||= User.new
	end

	def devise_mapping
	@devise_mapping ||= Devise.mappings[:user]
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friend_requests/index.html.erb
<div class="col-xs-12 col-md-12">
<h1>Buscar Amigos</h1>
<hr>
	<div class="row">
		<% @users.each do |user| %>	
			<div class="col-xs-6 col-md-2" align="center">
				<div class="friend-container thumbnail">
					<% if user.image.url() == '/images/original/missing.png' %>  
						<%= image_tag("missing.png", :class => "user-prof-image") %>
						<% else %>
						 <%= image_tag(user.image.url(), :class => "user-prof-image") %>   
					<% end %>    
				</div>
				<%= link_to "Solicitar Amistad", "/friend_requests/#{user.id}/create", method: :put, :class => "btn btn-success a-color" %>
			</div>				
		<% end %>
	</div>
</div>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/index.html.erb
<h1>Friends#index</h1>
<p>Find me in app/views/friends/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <title>Projec name</title>
  <link href='http://fonts.googleapis.com/css?family=Dosis:300,400,700' rel='stylesheet' type='text/css'>
  <script src="https://use.fontawesome.com/8a47688c13.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>
        project_url = {'base_url': '<%= request.base_url %>'}        
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "partials/menu" %>
	<div class="wrap m-top-50">
        <div class="container">
            <% if notice %>
                <div class="col-xs-12 col-md-12" align="center" id="success-notifi">
                    <div class="alert alert-success noti-all notifi" role="alert"><%= notice %>
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-top: -18px;cursor: pointer;">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                </div>
            <% end %>
            <% if alert %>
                <div class="col-xs-12 col-md-12" align="center" id="error-notifi">
                    <div class="alert alert-danger noti-all notifi" role="alert"><%= alert %>
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-top: -18px;cursor: pointer;">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                </div>
            <% end %>
            <%= yield %>
        </div>
    </div>
    <div class="t-foot"></div>
    <footer class="footer">
            <span>Copyright © 2016 - Todos los derechos reservados Jeyson Garcia</span>
    </footer>
    <audio id="chatAudio"><source src="/sounds/notification_2.mp3" type="audio/mpeg"></audio>
</body>
</html>

app/views/partials/_menu.html.erb
<header>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Project name</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><%= link_to "Inicio", root_path %></li>-->
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Mi perfil", profile_path(current_user.id) %></li>
          <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Crear cuanta", new_user_registration_path %></li>
          <li><%= link_to "Iniciar sesion", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/users/index.html.erb
<div class="row">
	<% @users.each do |user| %>	
		<div class="col-xs-6 col-md-2">
			<div class="friend-container thumbnail">
				<% if user.image.url() == '/images/original/missing.png' %>  
					<%= image_tag("missing.png", :class => "user-prof-image") %>
					<% else %>
					 <%= image_tag(user.image.url(), :class => "user-prof-image") %>   
				<% end %>    
			</div>
			<!--<%= link_to "Solicitar Amistad", "/friend_requests/#{user.id}/create", method: :put, :class => "btn btn-success a-color" %>-->
		</div>				
	<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
  <div class="thumbnail cont-profile-image">
      <% if @user_profile.image.url() == '/images/original/missing.png' %>  
        <%= image_tag("missing.png", :class => "user-prof-image") %>
        <% else %>
         <%= image_tag(@user_profile.image.url(), :class => "media-object img-box-user") %>   
      <% end %>        
  </div>

      <% if @user_profile.portada.url() == '/portadas/original/missing.png' %>
        <div class="jumbotron jumbo-profile" style="background-image: url(<%= image_path("missing-portada.jpg") %>);background-size: 100%;">      
        <% else %>
        <div class="jumbotron jumbo-profile" style="background-image: url(<%= @user_profile.portada.url() %>);background-size: 100%;">  
      <% end %> 

      <% if @user_profile.id == current_user.id and user_signed_in? %>
        <div class="container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-12">
            <div>
              <h4 class="text-profile-name thumbnail"><%= @user_profile.first_name %> <%= @user_profile.last_name %></h4>    
              
            </div>
            </div>
            <div class="col-xs-3 col-sm-2 col-md-2">
              <div class="btn-edit-profile thumbnail">
                <a class="fa fa-pencil-square-o" href="<%= edit_user_registration_path(current_user)%>"></a>
              </div>
              <div class="btn-banner-profile thumbnail">
                <a class="fa fa-address-card" href="#" data-toggle="modal" data-target="#myModal"></a>
              </div>
            </div>            
          </div>
        </div>
        
        
      <% end %>      
    </div>
    <div style="margin-top: 16%;">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Muro</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Amigos</a></li>
        <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Galeria</a></li>
        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Videos</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">...</div>
        <div role="tabpanel" class="tab-pane" id="profile">
          <div class="col-xs-12 col-md-12">
            <h1>Buscar Amigos</h1>
            <hr>
              <div class="row">
                <% @profiles.each do |profile| %> 
                  <div class="col-xs-6 col-md-2" align="center">
                    <div class="friend-container thumbnail">
                      <% if profile.image.url() == '/images/original/missing.png' %>  
                        <%= image_tag("missing.png", :class => "user-prof-image") %>
                        <% else %>
                         <%= image_tag(profile.image.url(), :class => "user-prof-image") %>   
                      <% end %>    
                    </div>
                    <!--<%= link_to "Eliminar Amistad", "/friend_requests/#{profile.id}/create", method: :put, :class => "btn btn-success a-color" %>-->
                  </div>        
                <% end %>
              </div>
          </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="messages">...</div>
        <div role="tabpanel" class="tab-pane" id="settings">...</div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, :multipart => true }) do |f| %>
            <%= devise_error_messages! %>
            <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                      <h4 class="modal-title" id="myModalLabel">Editar portada</h4>
            </div>
            <div class="modal-body">  
              <div class="form-group"> 
                <span>Se recomienda una foto con resolucion de 1110x266 de lo contrario sera recortada automaticamente</span>
                <br>
                <% User.all.each do |item| %>
                  <% if item.id == current_user.id %>
                    <% if item.portada_file_name == nil %>
                      <span>No hay imagen</span> 
                    <% else %>
                      <img src="<%= item.portada.url() %>" class="media-object" style="width: 100%;">          
                    <% end %>       
                  <% end %>
                <% end %>
                <br>
               <input name="user[portada]" id="user_portada" type="file">
              </div>        
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Actualizar Portada</button>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <%= render "users/chat" %>
</div>